FROM python:3.9
RUN pip install -U pip
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY ./backend_dumper.py ./backend_dumper.py

EXPOSE 5002
ENTRYPOINT ["python", "backend_dumper.py"]
