services:
  cassandra-node1:
    image: bitnami/cassandra:latest
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_DATACENTER=datacenter1
    networks:
      - ikea-ordering-kafka_default

#  web-app:
#    build: ./Dockerfile
#    restart: on-failure
#    environment:
#      - CASSANDRA_SEEDS=cassandra-node1
#      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
#      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
#      - CASSANDRA_PORT=${CASSANDRA_PORT}
#    ports:
#      - 5555:5555
#    depends_on:
#      - cassandra-node1
#    networks:
#      - ikea-ordering-kafka_default

  orders_backend:
    restart: always
    image: orders_backend:v1
    ports:
      - "5002:5002"
    networks:
      - ikea-ordering-kafka_default

  transactions_backend:
    restart: always
    image: transactions_backend:v1
    ports:
      - "5003:5003"
    networks:
      - ikea-ordering-kafka_default
networks:
  ikea-ordering-kafka_default:
    external: true